#! /bin/sh

sxhkd &

# Use compton if you want a transparent bar, etc.
compton &

killall -q redshift

while pgrep -u $UID -x redshift; do sleep 1; done

redshift &

# Set background image
# feh --bg-center /home/kwaddle/Pictures/Wallpapers/among_trees.png
feh --bg-center /home/kwaddle/Pictures/Wallpapers/among_trees_1.jpg

# Launch polybar
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
