#! /bin/sh

# What's this do?
sxhkd &

# Turn on the blue light filter
# killall -q redshift

# Wait until redshift is really dead to start a new one
# while pgrep -u $UID -x redshift > /dev/null; do sleep 1; done

# redshift &

# Use compton if you want a transparent bar etc., or turn off for efficiency
compton &

# Swap control and caps lock
/usr/bin/setxkbmap -option "ctrl:swapcaps"

# Set background image
# Use super + alt + r to reload your config
feh --bg-fill /home/kwaddle/Pictures/Wallpapers/spring_street.jpeg

# Launch polybar
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
